#################################
#             Shadows           #
#################################

shadow = true;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
# shadow-opacity = .75
# shadow-color = "#000000"

#################################
#           Fading              #
#################################

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
# fade-delta = 10

#################################
#   Transparency / Opacity      #
#################################

frame-opacity = 0.9;
# inactive-dim-fixed = true

#################################
#           Corners             #
#################################

corner-radius = 0

#################################
#            Blur               #
#################################

blur-background = true;
blur-method = "dual_kawase";
blur-strength = 5;
blur-kern = "3x3box";

#################################
#       General Settings        #
#################################

# Fixed the typo "bbackend" to "backend"
backend = "glx";
dithered-present = false;
vsync = true;
detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;
use-damage = true;

#################################
#             Rules             #
#################################

rules: ({
  match = "window_type = 'tooltip'";
  fade = false;
  shadow = true;
  opacity = 0.75;
  full-shadow = false;
}, {
  match = "window_type = 'dock'    || "
          "window_type = 'desktop' || "
          "_GTK_FRAME_EXTENTS@";
  blur-background = false;
}, {
  # --- THUNAR BLUR RULE ---
  # We set opacity here so the blur can be seen through the window
  match = "class_g = 'Thunar'";
  opacity = 0.85;
  blur-background = true;
}, {
  match = "window_type != 'dock'";
  # shader = "my_shader.frag";
}, {
  match = "window_type = 'dock' || "
          "window_type = 'desktop'";
  corner-radius = 0;
}, {
  match = "name = 'Notification'   || "
          "class_g = 'Conky'       || "
          "class_g ?= 'Notify-osd' || "
          "class_g = 'Cairo-clock' || "
          "_GTK_FRAME_EXTENTS@";
  shadow = false;
})